# fast motor tempo processing script
#
# input: rawdata df generated by 2017-11-27_raw_data_import.R script
# outputs: 5 csv files and several plots 
#   fast_filter1_counts_2017-12-05.csv  # tap_int counts after filter 1
#   fast_filter1_block_counts_2017-12-05.csv # block counts after filter 1
#   fast_filter2_data_2017-12-05.csv # raw tap_int data with filter 2 inclusion column
#   fast_filter2_counts_2017-12-05.csv # tap_int counts after filters 1 and 2
#   fast_filter2_summary_2017-12-05.csv # summary by participant of tempo after filters 1 and 2


# select fast MT data & preview graphically ----
fast <- rawdata %>% filter(task=="fast") %>% arrange(subject)

# PREFILTER: basic info about the data set
length(unique(fast$subject)) # IU: 228 subjects, MSU: 94 subjects
tmp <- unique(fast$subject) 
tail(tmp) # IU: P245 is final subject, MSU: P102 is final subject
summary(fast$tap_int) # IU: mean 270, median 195

# PREFILTER: overall by-block means (blocks consistent but LOTS of outliers in overall group)
fast %>%
  ggplot(aes(x=block, y=tap_int, group=block, color=block)) +
  geom_boxplot() + coord_cartesian(ylim=c(0,2500)) # arbitrary zoom-in

fast %>% ggplot(aes(x=tap_int)) + geom_histogram(bins=1000) + coord_cartesian(xlim=c(0,2000))

# PREFILTER: spot check individual participant's data spread
fast %>%
  filter(subject==241) %>%
  ggplot(aes(x=block, y=tap_int, group=block, color=block)) +
  geom_boxplot()


# FAST FILTER 1.1 (rm1, rm<75ms) & counts (export csv) ----
# exclude tap intervals that were first in trial or that are below 75 ms as a priori outliers or errors

# add include columns for != 1st, > 75 ms, and summary of both
fast_filter1 <- fast %>%
  mutate(tap_incl_rmfirst = ifelse(tap_index == 1, 0, 1),
         tap_incl_rm75ms = ifelse(tap_int < 75, 0, 1)) %>%
  # include summary column
  mutate(tap_include = ifelse(tap_index == 1, 0, # exclude if first tap of trial
                              ifelse(tap_int < 75, 0, 1))) 

# summary counts by P and block for loss for rm1st and <75 exclusion criteria
fast_filter1_counts <- fast_filter1 %>%
  group_by(subject,task,block) %>%
  summarize(n_total = n(),
            n_after_rm1 = sum(tap_incl_rmfirst),
            loss_rm1 = n_total - n_after_rm1,
            n_after_rm75 = sum(tap_incl_rm75ms),
            loss_rm75 = n_total - n_after_rm75)

# save as csv for future reference
write.csv(fast_filter1_counts, "fast_filter1_counts_2017-12-08.csv")


# quick summary counts for overall sample
sum(fast_filter1_counts$n_total, na.rm = TRUE) # IU: 13964 taps, MSU: 5291 taps
sum(fast_filter1_counts$n_after_rm1, na.rm = TRUE)  # IU: 13508 taps after rm1 (456 loss), MSU: 5103 after rm1 (188 loss)
summary(fast_filter1_counts$loss_rm1)
sum(fast_filter1_counts$n_after_rm75, na.rm = TRUE) # IU: 13961 taps after rm 75ms (so only 3 cut for this), MSU: 5273 after rm75 (18 lost)


# FAST FILTER 1 - Summarize taps after filter 1.1 by participant and block ----
# add include column for blocks with nints <= 5 and obtain median cut-offs for filter 2  
fast_filter1_summary <- fast_filter1 %>%
  filter(tap_include==1) %>%
  group_by(subject,task,block) %>%
  # may not need all these summary measures...
  summarize(nints = n(),
            mean = mean(tap_int, na.rm = TRUE),
            sd = sd(tap_int, na.rm = TRUE),
            median = median(tap_int, na.rm = TRUE), 
            IQR = quantile(tap_int, .75) - quantile(tap_int, .25),
            SIQR = .5*(quantile(tap_int, .75) - quantile(tap_int, .25))) %>% 
  # flag block with 0 if < 5 intervals in that block, plus addl measures i may not need...
  mutate(se = sd/sqrt(nints),
         cv_with_sd = sd/mean,
         cv = SIQR/median,
         block_incl_rm5 = ifelse(nints <= 5 , 0, 1))


# Counts for FAST FILTER 1.2 (rmblocks<5 ints) ----
# count for excluding blocks with fewer than 5 taps (after rm1 and rm75ms exclusions)

# summary counts of tap intervals by P for loss for rm nints < 5 criterion (counted ints AFTER rm1 and rm75)
# number of tap_ints lost     
fast_filter1_counts <- fast_filter1_counts %>%
  # criterion was <= 5 ints after rm1 and rm75
  mutate(loss_rm1_and_rm75 = loss_rm1 + loss_rm75,
         n_after_both = n_total - loss_rm1_and_rm75,
         loss_rmblocks = ifelse(n_after_both <= 5, n_after_both, 0),
         n_after_all = n_after_both - loss_rmblocks)

# re-save with addl block loss info (count of individual ints) - same filename as above, updating file
write.csv(fast_filter1_counts, "fast_filter1_counts_2017-12-08.csv")

# number of blocks lost 
fast_filter1_block_counts <- fast_filter1_summary %>%
  group_by(subject,task) %>%
  summarize(n_blocks = n(),
            n_after_rm5 = sum(block_incl_rm5),
            loss_rm5 = n_blocks - n_after_rm5) 

# save as csv for future reference
write.csv(fast_filter1_block_counts, "fast_filter1_block_counts_2017-12-08.csv")


# FAST FILTER 2 based on median by block (export csv), quick plots, & counts (export csv) ----

# removing bad blocks and filter1 tap ints before combining summary info with raw tap ints (only good ones)
fast_filter2 <- fast_filter1_summary %>%
  filter(block_incl_rm5 == 1) %>% # here, filtering by 1.2. already filtered by 1.1 in summary step.
  select(subject, task, block, nints, median, IQR, mean, sd) %>%
  left_join(fast_filter1[fast_filter1$tap_include == 1,], by = c("subject", "task", "block")) %>% # replicates summary info for each tap interval
  mutate(upper_cut_bymedian = 1.5*median,
         lower_cut_bymedian = 0.5*median,
         tap_incl_rm_med_up = ifelse(tap_int > upper_cut_bymedian, 0, 1),
         tap_incl_rm_med_low = ifelse(tap_int < lower_cut_bymedian, 0, 1),
         tap_incl_median = ifelse(tap_incl_rm_med_up == 0 | 
                                    tap_incl_rm_med_low == 0, 0, 1))

# save for easy access...
write.csv(fast_filter2, "fast_filter2_data_2017-12-08.csv")


# boxplot tap_ints after filter 2: overall by-block medians - looks much better than filter 1
fast_filter2 %>%
  filter(tap_incl_median==1) %>%
  ggplot(aes(x=block, y=tap_int, group=block, color=block)) +
  geom_boxplot() + coord_cartesian(ylim=c(0,1000)) + # arbitrary zoom-in
  theme_classic() +
  labs(title = 'Fast MT (MSU, N=94)', # 'Fast MT (IU, N=171)'
       x = 'Block', 
       y = 'Tap Interval (ms)')

# density plot tap_ints after filter 2
fast_filter2 %>% 
  filter(tap_incl_median==1) %>%
  ggplot(aes(x=tap_int, group=block, color=block, fill=block)) + 
  #geom_histogram(binwidth=25, alpha=.5, position="dodge") +
  geom_density(alpha=.3) +
  # add median by block as vertical line?
  # geom_vline(aes(xintercept=mean(tap_int, na.rm=T)),   # Ignore NA values for mean
  #           color="black", linetype="dashed", size=1) +
  theme_classic() +
  labs(title = 'Fast MT (MSU, N=94)', # 'Fast MT (IU, N=171)'
       x = 'Median Tap Interval (ms)', 
       y = 'Count') #+
#facet_grid(block~.)

# filter 2: check single participant 
fast_filter2 %>%
  filter(tap_incl_median==1, 
         subject==245) %>%
  ggplot(aes(x=block, y=tap_int, group=block, color=block)) +
  geom_boxplot() + # to see boxplot
  geom_point(alpha = .5, position="jitter") # to see cloud of points in addition / instead


# summary counts by P and block for loss for each median cut-off and both together
fast_filter2_counts <- fast_filter2 %>%
  group_by(subject,task,block) %>%
  summarize(n_after_filter1 = n(),
            n_after_rm_low = sum(tap_incl_rm_med_low),
            n_after_rm_up = sum(tap_incl_rm_med_up),
            n_after_rm_median = sum(tap_incl_median),
            loss_after_rm_low = n_after_filter1 - n_after_rm_low, # __ lost total
            loss_after_rm_up = n_after_filter1 - n_after_rm_up, # ___ lost total
            loss_after_rm_median = n_after_filter1 - n_after_rm_median)

write.csv(fast_filter2_counts, "fast_filter2_counts_2017-12-08.csv")


# FAST FILTER 2 - SUMMARY BY PARTICIPANT  ----

# first, summary by P and block re-calculating block medians (i.e. different from in fast_filter2) AFTER implementing median filter
fast_filter2_summary_byP <- fast_filter2 %>%
  group_by(subject, task, block) %>%
  filter(tap_incl_median == 1) %>%
  summarize(nints_f2 = n(),
            median_f2 = median(tap_int, na.rm=TRUE),
            IQR_f2 = quantile(tap_int, .75) - quantile(tap_int, .25),
            mean_f2 = mean(tap_int, na.rm=TRUE),
            sd_f2 = sd(tap_int, na.rm=TRUE)) %>%
  gather(temp, measure, c("nints_f2", "median_f2", "IQR_f2", "mean_f2", "sd_f2")) %>%
  unite(temp1, block, temp, sep = ".") %>% 
  spread(temp1, measure) %>%
  rename(b1_median_f2 = "1.median_f2", b2_median_f2 = "2.median_f2",
         b1_IQR_f2 = "1.IQR_f2", b2_IQR_f2 = "2.IQR_f2",
         b1_nints_f2 = "1.nints_f2", b2_nints_f2= "2.nints_f2",
         b1_mean_f2 = "1.mean_f2", b2_mean_f2 = "2.mean_f2",
         b1_sd_f2 = "1.sd_f2", b2_sd_f2 = "2.sd_f2") %>%
  mutate(mean_medtempo = mean(c(b1_median_f2, b2_median_f2), na.rm=TRUE))

write.csv(fast_filter2_summary_byP, "fast_filter2_summary_2017-12-08.csv")


# overall views of the fast mt data            
fast_filter2_summary_byP %>%
  ggplot(aes(x=task, y=mean_medtempo)) + geom_boxplot()

fast_filter2_summary_byP %>% ggplot(aes(x=mean_medtempo)) + geom_histogram(bins=25)

summary(fast_filter2_summary_byP$mean_medtempo) # IU: mean 215, median 192


# histogram filter 2
fast_filter2_summary_byP %>% 
  ggplot(aes(x=mean_medtempo, fill=task)) + 
  geom_histogram(binwidth=50, alpha=.5) + # position="dodge"
  #geom_density(alpha=.3) +
  # add median by block as vertical line?
  # geom_vline(aes(xintercept=mean(tap_int, na.rm=T)),   # Ignore NA values for mean
  #           color="black", linetype="dashed", size=1) +
  theme_classic() +
  labs(title = 'Mean Fast MT (MSU, N=94)', #'Mean Fast MT (IU, N=171)', 
       x = 'Mean of Block Medians (ms)', 
       y = 'Count')


# variability plots -----
plots_df <- fast_filter2 %>%
  group_by(subject, task, block) %>%
  filter(tap_incl_median == 1) %>%
  summarize(nints = n(),
            median = median(tap_int, na.rm=TRUE),
            IQR = quantile(tap_int, .75) - quantile(tap_int, .25),
            mean = mean(tap_int, na.rm=TRUE),
            sd = sd(tap_int, na.rm=TRUE)) %>%
  mutate(qcv = IQR/median, # quartile-based CV
         cv = sd/mean)

# IQR / median
plots_df %>%
  ggplot(aes(x=median, y=IQR, color=block)) +
  geom_point(size=3) +
  geom_smooth(method=lm, se=FALSE) +
  theme_classic() +
  labs(title = 'Fast MT IQR/Median (MSU, N=94)', # 'Fast MT IQR/Median (IU, N=171)', 
       x = 'Block Median (ms)', 
       y = 'Block IQR (ms)')

plots_df %>%
  ggplot(aes(x=block, y=qcv, color=block)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = 'Fast MT - Quartile based CV (MSU, N=94)', # 'Fast MT - Quartile based CV (IU, N=171)', 
       x = 'Block', 
       y = 'QCV = IQR/median')


# SD / mean 
plots_df %>%
  ggplot(aes(x=mean, y=sd, color=block)) +
  geom_point(size=3) +
  geom_smooth(method=lm, se=FALSE) +
  labs(title = 'Fast MT SD/Mean (MSU, N=94)', # 'Fast MT SD/Mean (IU, N=171)', 
       x = 'Block Mean (ms)', 
       y = 'Block SD (ms)') 

plots_df %>%
  ggplot(aes(x=block, y=cv, color=block)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = 'Fast MT CV (MSU, N=94)', # 'Fast MT CV (IU, N=171)', 
       x = 'Block', 
       y = 'CV = SD/Mean')


# starting from wide summary df (just to check):
fast_filter2_summary_byP %>%
  ggplot(aes(x=b1_median_f2, y=b1_IQR_f2)) +
  geom_point(size=3) + geom_smooth(method=lm, se=FALSE)

fast_filter2_summary_byP %>%
  ggplot(aes(x=b1_mean_f2, y=b1_sd_f2)) +
  geom_point(size=3) + geom_smooth(method=lm, se=FALSE)



